name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      run: |
        sudo apt update
        sudo apt install -y ninja-build clang cmake \
            vulkan-sdk libvulkan-dev vulkan-utility-libraries-dev spirv-tools glslang-tools \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
            libwayland-dev libxkbcommon-dev

    - name: Configure with CMake (Linux)
      run: |
        cmake -S . -B out \
              -G Ninja \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Release -DWAYLAND=true

    - name: Build with CMake (Linux)
      run: cmake --build out

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
       version: 1.4.309.0
       cache: true
    - name: Configure with CMake (Windows)
      run: |
        cmake -S . -B out -G "Visual Studio 17 2022" -A x64 -T ClangCL -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake (Windows)
      run: cmake --build out
